version: '3.9'

services:

    laravel:
        build:
            context: .
            dockerfile: ./docker/laravel/Dockerfile
        image: laravel:latest
        container_name: laravel
        stdin_open: true
        tty: true
        environment:
            TZ: ${TIME_ZONE}
        working_dir: /var/www/html
        networks:
            - network
        volumes:
            - ./:/var/www/html:z
        depends_on:
            - database


    database:
        image: mariadb
        container_name: mariadb
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
            TZ: ${TIME_ZONE}
        volumes:
            - ./docker/volumes/database:/var/lib/mysql:z
        networks:
            - network

    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - '8082:80'
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            TZ: ${TIME_ZONE}
        networks:
            - network


    nginx:
        image: nginx:alpine
        container_name: nginx
        hostname: ${APP_URL}
        tty: true
        environment:
            TZ: ${TIME_ZONE}
            DOMAIN: ${APP_URL}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - network
        depends_on:
            - laravel
            - database
            - phpmyadmin

networks:
    network:
        driver: bridge
